"""create_password_reset_model

Revision ID: 8a14722c7b0a
Revises: bbe3dc4d86a3
Create Date: 2025-11-19 00:00:14.445369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8a14722c7b0a'
down_revision: Union[str, Sequence[str], None] = 'bbe3dc4d86a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_email'), 'password_reset', ['email'], unique=False)
    op.create_index(op.f('ix_password_reset_id'), 'password_reset', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_id'), table_name='password_reset')
    op.drop_index(op.f('ix_password_reset_email'), table_name='password_reset')
    op.drop_table('password_reset')
    # ### end Alembic commands ###
